X1CA_Coop_002/X1CA_Coop_002_m4qaiai.lua

Added two platoons with battleships in last part of the mission, built only if player has some T3 naval units.

Battleship platoons for QAI

---

X1CA_Coop_005/X1CA_Coop_005_m3qaiai.lua

This will spice things up a little bit.

Battleship platoon for QAI FA M5

---

SCCA_Coop_E05/SCCA_Coop_E05_script.lua

Added restrictions to FA units + moved restrictions  from AI to player so it actually has some effect

UEF M5 Fixed Restrictions

---

SCCA_Coop_E06/SCCA_Coop_E06_script.lua

one was breaking script, mission didnt launch properly. And added restrictions to FA units.

UEF M6 Fixed Restrictions

---

X1CA_Coop_001/X1CA_Coop_001_script.lua

Only one of two bases got cleaned from player's radar and only two from four arty positions. This will fix it.

Properly cleaning Intel

---

SCCA_Coop_A02/SCCA_Coop_A02_script.lua
SCCA_Coop_A03/SCCA_Coop_A03_script.lua
SCCA_Coop_A04/SCCA_Coop_A04_script.lua
SCCA_Coop_A05/SCCA_Coop_A05_script.lua
SCCA_Coop_E02/SCCA_Coop_E02_script.lua
SCCA_Coop_E03/SCCA_Coop_E03_script.lua
SCCA_Coop_E04/SCCA_Coop_E04_script.lua
SCCA_Coop_E06/SCCA_Coop_E06_script.lua
SCCA_Coop_R02/SCCA_Coop_R02_script.lua
SCCA_Coop_R03/SCCA_Coop_R03_script.lua

Allowing player to build support factories where he's given HQs

Support Fac Restrictions

---

X1CA_Coop_004/X1CA_Coop_004_script.lua

Maybe simple test if the missions starts would be worth the time to prevent this. Or PR where others could notice :P

Fixing typo FA M4

---

X1CA_Coop_001/X1CA_Coop_001_m4seraphimai.lua

Coming back to the original values that someone rewrote to some crazy numbers.

Better numbers of engies for FA M1

---

X1CA_Coop_001/X1CA_Coop_001_m4uefai.lua

This AI was never suppose to build fatboy, Base that you need to save can actually win on its own...

FA M1 Removing Fatboy

---

X1CA_Coop_002/X1CA_Coop_002_m3qaiai.lua

Making this base actually build something. Two T2 naval attack platoons.
Also increased base radius so plattons gets send on patrol.

FA M2 QAI Naval Attacks

---

X1CA_Coop_001/X1CA_Coop_001_script.lua

Hopefully will fix
http://forums.faforever.com/forums/viewtopic.php?f=3&t=10806&p=110252#p110040

Fixing Typo

---

SCCA_Coop_A01/SCCA_Coop_A01_script.lua
SCCA_Coop_A02/SCCA_Coop_A02_script.lua
SCCA_Coop_A03/SCCA_Coop_A03_script.lua
SCCA_Coop_A04/SCCA_Coop_A04_script.lua
SCCA_Coop_A05/SCCA_Coop_A05_script.lua
SCCA_Coop_A06/SCCA_Coop_A06_script.lua
SCCA_Coop_E01/SCCA_Coop_E01_script.lua
SCCA_Coop_E02/SCCA_Coop_E02_script.lua
SCCA_Coop_E03/SCCA_Coop_E03_script.lua
SCCA_Coop_E04/SCCA_Coop_E04_script.lua
SCCA_Coop_E05/SCCA_Coop_E05_script.lua
SCCA_Coop_E06/SCCA_Coop_E06_script.lua
SCCA_Coop_R01/SCCA_Coop_R01_script.lua
SCCA_Coop_R02/SCCA_Coop_R02_script.lua
SCCA_Coop_R03/SCCA_Coop_R03_script.lua
SCCA_Coop_R04/SCCA_Coop_R04_script.lua
SCCA_Coop_R05/SCCA_Coop_R05_script.lua
SCCA_Coop_R06/SCCA_Coop_R06_script.lua
X1CA_Coop_001/X1CA_Coop_001_script.lua
X1CA_Coop_002/X1CA_Coop_002_script.lua
X1CA_Coop_003/X1CA_Coop_003_script.lua
X1CA_Coop_004/X1CA_Coop_004_script.lua
X1CA_Coop_005/X1CA_Coop_005_script.lua
X1CA_Coop_006/X1CA_Coop_006_script.lua

Giving player and coop players different colors. Naming spawned ACUs.
Few typos fixed.
Removed warp in effect where ACUs spawn from gate, replaced by fake gate
in effect.

Different Colors for Players, Name ACUs

---

SCCA_Coop_A05/SCCA_Coop_A05_script.lua

Fixes  #106 #58 
allow harbingers for Ariel in the last part

Fix Blake's death playing twice

---

SCCA_Coop_A01/SCCA_Coop_A01_script.lua
SCCA_Coop_A02/SCCA_Coop_A02_script.lua
SCCA_Coop_A03/SCCA_Coop_A03_script.lua
SCCA_Coop_A04/SCCA_Coop_A04_script.lua
SCCA_Coop_A05/SCCA_Coop_A05_script.lua
SCCA_Coop_A06/SCCA_Coop_A06_script.lua
SCCA_Coop_E01/SCCA_Coop_E01_script.lua
SCCA_Coop_E02/SCCA_Coop_E02_script.lua
SCCA_Coop_E03/SCCA_Coop_E03_script.lua
SCCA_Coop_E04/SCCA_Coop_E04_script.lua
SCCA_Coop_E05/SCCA_Coop_E05_script.lua
SCCA_Coop_E06/SCCA_Coop_E06_script.lua
SCCA_Coop_R01/SCCA_Coop_R01_script.lua
SCCA_Coop_R02/SCCA_Coop_R02_script.lua
SCCA_Coop_R03/SCCA_Coop_R03_script.lua
SCCA_Coop_R04/SCCA_Coop_R04_script.lua
SCCA_Coop_R05/SCCA_Coop_R05_script.lua
SCCA_Coop_R06/SCCA_Coop_R06_script.lua
X1CA_Coop_001/X1CA_Coop_001_script.lua
X1CA_Coop_002/X1CA_Coop_002_script.lua
X1CA_Coop_003/X1CA_Coop_003_script.lua
X1CA_Coop_004/X1CA_Coop_004_script.lua
X1CA_Coop_005/X1CA_Coop_005_script.lua
X1CA_Coop_006/X1CA_Coop_006_script.lua

Using new function to split unit cap evenly among all present human
players.
Fixes #113

New Unit Cap Values

---

ThetaCivilianRescue/ThetaCivilianRescue_strings.lua

There was a sound missing for a dialog.

Add correct sound bank to dialog

---

SCCA_Coop_A05/SCCA_Coop_A05_save.lua

Reallign mexes in UEF base.

---

ThetaCivilianRescue/ThetaCivilianRescue_script.lua

ThetaCivilainRescue: Change to distinctive player colors

---

ThetaCivilianRescue/ThetaCivilianRescue_m1cybranai.lua

ThetaCivilianRescue: Don't let engineers rebuild forward defenses

---

Prothyon16/Prothyon16_m1uefai.lua
Prothyon16/Prothyon16_m2uefai.lua
Prothyon16/Prothyon16_m3uefai.lua
Prothyon16/Prothyon16_m5seraphimai.lua
Prothyon16/Prothyon16_m6seraphimai.lua
X1CA_Coop_001/X1CA_Coop_001_m1orderai.lua
X1CA_Coop_001/X1CA_Coop_001_m3orderai.lua
X1CA_Coop_001/X1CA_Coop_001_m4seraphimai.lua
X1CA_Coop_002/X1CA_Coop_002_m1orderai.lua
X1CA_Coop_002/X1CA_Coop_002_m2orderai.lua
X1CA_Coop_002/X1CA_Coop_002_m2qaiai.lua
X1CA_Coop_002/X1CA_Coop_002_m3qaiai.lua
X1CA_Coop_002/X1CA_Coop_002_m4qaiai.lua
X1CA_Coop_003/X1CA_Coop_003_m1seraphimai.lua
X1CA_Coop_003/X1CA_Coop_003_m2seraphimai.lua
X1CA_Coop_003/X1CA_Coop_003_m3seraphimai.lua
X1CA_Coop_004/X1CA_Coop_004_m1seraphimai.lua
X1CA_Coop_004/X1CA_Coop_004_m2seraphimai.lua
X1CA_Coop_004/X1CA_Coop_004_m3seraphimai.lua
X1CA_Coop_005/X1CA_Coop_005_m1hex5ai.lua
X1CA_Coop_005/X1CA_Coop_005_m2hex5ai.lua
X1CA_Coop_005/X1CA_Coop_005_m3qaiai.lua
X1CA_Coop_006/X1CA_Coop_006_m1seraphimai.lua
X1CA_Coop_006/X1CA_Coop_006_m2fletcherai.lua
X1CA_Coop_006/X1CA_Coop_006_m2orderai.lua
X1CA_Coop_006/X1CA_Coop_006_m3seraphimai.lua

Use new function for triggers

---

SCCA_Coop_R01/SCCA_Coop_R01_save.lua
SCCA_Coop_R01/SCCA_Coop_R01_scenario.lua
SCCA_Coop_R01/SCCA_Coop_R01_script.lua
SCCA_Coop_R02/SCCA_Coop_R02_Editorfunctions.lua
SCCA_Coop_R02/SCCA_Coop_R02_save.lua
SCCA_Coop_R02/SCCA_Coop_R02_scenario.lua
SCCA_Coop_R02/SCCA_Coop_R02_script.lua
SCCA_Coop_R03/SCCA_Coop_R03_save.lua
SCCA_Coop_R03/SCCA_Coop_R03_scenario.lua
SCCA_Coop_R03/SCCA_Coop_R03_script.lua
SCCA_Coop_R04/SCCA_Coop_R04_save.lua
SCCA_Coop_R04/SCCA_Coop_R04_scenario.lua
SCCA_Coop_R04/SCCA_Coop_R04_script.lua
SCCA_Coop_R05/SCCA_Coop_R05_save.lua
SCCA_Coop_R05/SCCA_Coop_R05_scenario.lua
SCCA_Coop_R05/SCCA_Coop_R05_script.lua
SCCA_Coop_R06/SCCA_Coop_R06_save.lua
SCCA_Coop_R06/SCCA_Coop_R06_scenario.lua
SCCA_Coop_R06/SCCA_Coop_R06_script.lua

The Cybran mission changes for #158

RenameToPlayerX for Cybran missions

---

SCCA_Coop_E01/SCCA_Coop_E01_save.lua
SCCA_Coop_E01/SCCA_Coop_E01_scenario.lua
SCCA_Coop_E01/SCCA_Coop_E01_script.lua
SCCA_Coop_E02/SCCA_Coop_E02_aeonaiplan.lua
SCCA_Coop_E02/SCCA_Coop_E02_save.lua
SCCA_Coop_E02/SCCA_Coop_E02_scenario.lua
SCCA_Coop_E02/SCCA_Coop_E02_script.lua
SCCA_Coop_E03/SCCA_Coop_E03_save.lua
SCCA_Coop_E03/SCCA_Coop_E03_scenario.lua
SCCA_Coop_E03/SCCA_Coop_E03_script.lua
SCCA_Coop_E04/SCCA_Coop_E04_save.lua
SCCA_Coop_E04/SCCA_Coop_E04_scenario.lua
SCCA_Coop_E04/SCCA_Coop_E04_script.lua
SCCA_Coop_E05/SCCA_Coop_E05_save.lua
SCCA_Coop_E05/SCCA_Coop_E05_scenario.lua
SCCA_Coop_E05/SCCA_Coop_E05_script.lua
SCCA_Coop_E06/SCCA_Coop_E06_save.lua
SCCA_Coop_E06/SCCA_Coop_E06_scenario.lua
SCCA_Coop_E06/SCCA_Coop_E06_script.lua

The UEF mission changes for #158

RenameToPlayerX for UEF missions

---

SCCA_Coop_E01/SCCA_Coop_E01_save.lua
SCCA_Coop_E04/SCCA_Coop_E04_save.lua

Use new BuildConditions in _save files

---

SCCA_Coop_R05/SCCA_Coop_R05_script.lua

Cybran M5 Typo

---

SCCA_Coop_R03/SCCA_Coop_R03_script.lua

Don't share resources to players

---

X1CA_Coop_002/X1CA_Coop_002_m1orderai.lua

Fix wrong paths to trigger

---

X1CA_Coop_004/X1CA_Coop_004_script.lua

FAM4: Either have dialogue for kennel or for hives

---

X1CA_Coop_004/X1CA_Coop_004_script.lua

Use new system for the nuke projectiles

---

FortClarkeAssault/FortClarkeAssault_script.lua

Make sure transports won't die

---

FortClarkeAssault/FortClarkeAssault_script.lua
Prothyon16/Prothyon16_m3uefai.lua
Prothyon16/Prothyon16_m5seraphimai.lua
Prothyon16/Prothyon16_script.lua
SCCA_Coop_A03/SCCA_Coop_A03_script.lua
SCCA_Coop_E05/SCCA_Coop_E05_script.lua
SCCA_Coop_E06/SCCA_Coop_E06_script.lua
SCCA_Coop_R04/SCCA_Coop_R04_script.lua
SCCA_Coop_R06/SCCA_Coop_R06_script.lua
X1CA_Coop_004/X1CA_Coop_004_m3seraphimai.lua
X1CA_Coop_004/X1CA_Coop_004_script.lua
X1CA_Coop_005/X1CA_Coop_005_m3qaiai.lua
X1CA_Coop_005/X1CA_Coop_005_script.lua
X1CA_Coop_006/X1CA_Coop_006_script.lua

Count units of all human players

---

X1CA_Coop_001/X1CA_Coop_001_script.lua

Fix Gari's counterattack

---

SCCA_Coop_R06/SCCA_Coop_R06_script.lua

Fix endgame of C M6

---

NovaxStationAssault/NovaxStationAssault_m2cybranai.lua
NovaxStationAssault/NovaxStationAssault_m2uefai.lua

Fix Novax Station Build Conditions

---

X1CA_Coop_001/X1CA_Coop_001_script.lua

FA1: Add missing ScearioFrameworks

---

Prothyon16/Prothyon16_script.lua

Missed line when renaming Coop1 to Player2

---

FortClarkeAssault/FortClarkeAssault_save.lua
NovaxStationAssault/NovaxStationAssault_save.lua
OperationThaAthaAez/OperationThaAthaAez_save.lua
Prothyon16/Prothyon16_save.lua
SCCA_Coop_A01/SCCA_Coop_A01_save.lua
SCCA_Coop_A02/SCCA_Coop_A02_save.lua
SCCA_Coop_A03/SCCA_Coop_A03_save.lua
SCCA_Coop_A04/SCCA_Coop_A04_save.lua
SCCA_Coop_A05/SCCA_Coop_A05_save.lua
SCCA_Coop_A06/SCCA_Coop_A06_save.lua
SCCA_Coop_E01/SCCA_Coop_E01_save.lua
SCCA_Coop_E02/SCCA_Coop_E02_save.lua
SCCA_Coop_E03/SCCA_Coop_E03_save.lua
SCCA_Coop_E04/SCCA_Coop_E04_save.lua
SCCA_Coop_E05/SCCA_Coop_E05_save.lua
SCCA_Coop_E06/SCCA_Coop_E06_save.lua
SCCA_Coop_R01/SCCA_Coop_R01_save.lua
SCCA_Coop_R02/SCCA_Coop_R02_save.lua
SCCA_Coop_R03/SCCA_Coop_R03_save.lua
SCCA_Coop_R04/SCCA_Coop_R04_save.lua
SCCA_Coop_R05/SCCA_Coop_R05_save.lua
SCCA_Coop_R06/SCCA_Coop_R06_save.lua
ThetaCivilianRescue/ThetaCivilianRescue_save.lua
X1CA_Coop_001/X1CA_Coop_001_save.lua
X1CA_Coop_002/X1CA_Coop_002_save.lua
X1CA_Coop_003/X1CA_Coop_003_save.lua
X1CA_Coop_004/X1CA_Coop_004_save.lua
X1CA_Coop_005/X1CA_Coop_005_save.lua
X1CA_Coop_006/X1CA_Coop_006_save.lua

for FAForever/fa-coop#52 and FAForever/fa-coop#53
Simply used ACU or sACU positions.

Add Starting position markers for lobby mappreview

---

FortClarkeAssault/FortClarkeAssault_scenario.lua
NovaxStationAssault/NovaxStationAssault_scenario.lua
OperationThaAthaAez/OperationThaAthaAez_scenario.lua
Prothyon16/Prothyon16_scenario.lua
ThetaCivilianRescue/ThetaCivilianRescue_scenario.lua

Fixes #210
This value gets automatically changed by deployment script.

Add map version for custom missions

---

FortClarkeAssault/FortClarkeAssault_scenario.lua
NovaxStationAssault/NovaxStationAssault_scenario.lua
OperationThaAthaAez/OperationThaAthaAez_scenario.lua
Prothyon16/Prothyon16_scenario.lua
SCCA_Coop_A01/SCCA_Coop_A01_scenario.lua
SCCA_Coop_A02/SCCA_Coop_A02_scenario.lua
SCCA_Coop_A03/SCCA_Coop_A03_scenario.lua
SCCA_Coop_A04/SCCA_Coop_A04_scenario.lua
SCCA_Coop_A05/SCCA_Coop_A05_scenario.lua
SCCA_Coop_A06/SCCA_Coop_A06_scenario.lua
SCCA_Coop_E01/SCCA_Coop_E01_scenario.lua
SCCA_Coop_E02/SCCA_Coop_E02_scenario.lua
SCCA_Coop_E03/SCCA_Coop_E03_scenario.lua
SCCA_Coop_E04/SCCA_Coop_E04_scenario.lua
SCCA_Coop_E05/SCCA_Coop_E05_scenario.lua
SCCA_Coop_E06/SCCA_Coop_E06_scenario.lua
SCCA_Coop_R01/SCCA_Coop_R01_scenario.lua
SCCA_Coop_R02/SCCA_Coop_R02_scenario.lua
SCCA_Coop_R03/SCCA_Coop_R03_scenario.lua
SCCA_Coop_R04/SCCA_Coop_R04_scenario.lua
SCCA_Coop_R05/SCCA_Coop_R05_scenario.lua
SCCA_Coop_R06/SCCA_Coop_R06_scenario.lua
ThetaCivilianRescue/ThetaCivilianRescue_scenario.lua
X1CA_Coop_001/X1CA_Coop_001_scenario.lua
X1CA_Coop_002/X1CA_Coop_002_scenario.lua
X1CA_Coop_003/X1CA_Coop_003_scenario.lua
X1CA_Coop_004/X1CA_Coop_004_scenario.lua
X1CA_Coop_005/X1CA_Coop_005_scenario.lua
X1CA_Coop_006/X1CA_Coop_006_scenario.lua

Restrict which factions can be chosen for each mission.
Using this feature : FAForever/fa#1658

Add faction restrictions

---

SCCA_Coop_E01/SCCA_Coop_E01_scenario.lua

UEFM1: Fix too many Player2

---

SCCA_Coop_E02/SCCA_Coop_E02_script.lua

UEF M2 Disable Friendly AI Resource Sharing

---

SCCA_Coop_E03/SCCA_Coop_E03_script.lua

UEF M3 Disable Friendly AI Resource Sharing

---

SCCA_Coop_E02/SCCA_Coop_E02_script.lua

UEF M2 Fix Aeon ACU not exploding

---

SCCA_Coop_A01/SCCA_Coop_A01_script.lua
SCCA_Coop_E01/SCCA_Coop_E01_script.lua
SCCA_Coop_E03/SCCA_Coop_E03_script.lua
SCCA_Coop_R01/SCCA_Coop_R01_script.lua
SCCA_Coop_R06/SCCA_Coop_R06_script.lua

Use the changes from this PR: FAForever/fa#1707

Change StatCompare Objective so it considers all HumanPlayers

---

X1CA_Coop_002/X1CA_Coop_002_script.lua

Only 1 map needed it :(
fixes #131 (i think? right? or is there something else?)

Use new CategoriesInArea feature

---

SCCA_Coop_E01/SCCA_Coop_E01_script.lua

matched restrictions for capturable units
repaced ras for gun upgrade

Adjust restrictions

---

X1CA_Coop_002/X1CA_Coop_002_script.lua

Fix jester unlock dialogue playing twice

---

SCCA_Coop_E05/SCCA_Coop_E05_script.lua

Fix intro dialogue, lazy var error

---

SCCA_Coop_A03/SCCA_Coop_A03_script.lua

Fixes https://github.com/FAForever/fa-coop/issues/67

Fix wrong cleanup

---

X1CA_Coop_006/X1CA_Coop_006_script.lua

Fix option zero nukes work only with first player

---

SCCA_Coop_R04/SCCA_Coop_R04_script.lua
SCCA_Coop_R05/SCCA_Coop_R05_script.lua

Fixes the replays + potential desyncs

Use first army for viz markers

---

SCCA_Coop_A04/SCCA_Coop_A04_m1nexusai.lua
SCCA_Coop_A04/SCCA_Coop_A04_script.lua

Fix TML shooting right away

---

FAF_Coop_Havens_Invasion/FAF_Coop_Havens_Invasion_save.lua

Fix wrong group name

---

SCCA_Coop_E02/SCCA_Coop_E02_script.lua

UEF M2 Reduce the delay before the Aeon attack

---

SCCA_Coop_A05/SCCA_Coop_A05_script.lua

Aeon M5 Allow omni when the map expands

---

SCCA_Coop_A03/SCCA_Coop_A03_script.lua

Aeon M3 Better values for bonus objectives

---

FAF_Coop_Havens_Invasion/FAF_Coop_Havens_Invasion_script.lua

HI - Make sure the ACU doesnt die during cinematics

---

X1CA_Coop_001/X1CA_Coop_001_script.lua

Fixes #318 
Needs to be tested with all 3 factions.
3 games, in each different faction for the first player, other 2 factions taking the others spots.

FAM1 - Fix desync with Aeon player

---

X1CA_Coop_006/X1CA_Coop_006_script.lua

Fix Vendetta's taunt playing when she's dead

---

SCCA_Coop_A02/SCCA_Coop_A02_script.lua
SCCA_Coop_E05/SCCA_Coop_E05_script.lua
SCCA_Coop_R03/SCCA_Coop_R03_script.lua
X1CA_Coop_002/X1CA_Coop_002_script.lua

This is the work which needed doing for my rebase branch on FAF
Untested but I see no problems
- Unsure about one of them, where there's a GPG-era comment requesting gate-ins, but the code was actually calling the unit-side blast entrance... What to do?

Use spawn commander

---

FAF_Coop_Fort_Clarke_Assault/FAF_Coop_Fort_Clarke_Assault_script.lua
FAF_Coop_Operation_Rescue/FAF_Coop_Operation_Rescue_script.lua
FAF_Coop_Operation_Tha_Atha_Aez/FAF_Coop_Operation_Tha_Atha_Aez_script.lua
FAF_Coop_Operation_Uhthe_Thuum_QAI/FAF_Coop_Operation_Uhthe_Thuum_QAI_script.lua
FAF_Coop_Operation_Yath_Aez/FAF_Coop_Operation_Yath_Aez_script.lua
FAF_Coop_Theta_Civilian_Rescue/FAF_Coop_Theta_Civilian_Rescue_script.lua
X1CA_Coop_001/X1CA_Coop_001_script.lua
X1CA_Coop_006/X1CA_Coop_006_script.lua
changelog.md

Need accept together with this PR and other PR by link below.
[Link to fix save Timed Expansion lobby option](https://github.com/FAForever/fa-coop/pull/87)

Delete duplicate code in PlayerDeath function and added compatibility with Timed Expansion lobby option

---

SCCA_Coop_E05/SCCA_Coop_E05_script.lua
SCCA_Coop_R02/SCCA_Coop_R02_script.lua
SCCA_Coop_R05/SCCA_Coop_R05_script.lua
SCCA_Coop_R06/SCCA_Coop_R06_script.lua

This allows black ops or any other mod tha replaces the ACU to still fire the trigger

Use COMMAND cat for mission triggers instead of unit specific

---

FAF_Coop_Operation_Blockade/FAF_Coop_Operation_Blockade_script.lua
FAF_Coop_Operation_Holy_Raid/FAF_Coop_Operation_Holy_Raid_script.lua
FAF_Coop_Operation_Ioz_Shavoh_Kael/FAF_Coop_Operation_Ioz_Shavoh_Kael_script.lua
FAF_Coop_Operation_Tha_Atha_Aez/FAF_Coop_Operation_Tha_Atha_Aez_script.lua
FAF_Coop_Operation_Uhthe_Thuum_QAI/FAF_Coop_Operation_Uhthe_Thuum_QAI_script.lua
FAF_Coop_Operation_Yath_Aez/FAF_Coop_Operation_Yath_Aez_script.lua

See https://github.com/FAForever/faf-coop-maps/issues/362#issuecomment-1192984754

Updates coop maps to correctly use the TimedExpansion option

---

X1CA_Coop_005/X1CA_Coop_005_script.lua

Need a space for all the storages that got added earlier

FA M5 Increase Fletcher's unit cap

---

FAF_Coop_Operation_Blockade/FAF_Coop_Operation_Blockade_script.lua

Fix syntax error in Op Blockade

---

SCCA_Coop_R02/SCCA_Coop_R02_script.lua

Increase ACU detection area around the gate

---

SCCA_Coop_A06/SCCA_Coop_A06_script.lua

Make Marxon Invincible while teleporting

---

SCCA_Coop_R04/SCCA_Coop_R04_script.lua

Fix syntax

---

FAF_Coop_Operation_Rebel's_Rest/FAF_Coop_Operation_Rebel's_Rest_strings.lua
FAF_Coop_Operation_Red_Revenge/FAF_Coop_Operation_Red_Revenge_strings.lua

Fixed a few spelling and grammar issues in the strings for the following:
* Rebel's Rest
* Red Revenge

[Strings] Fixed spelling and grammar issues in new campaign missions

---

FAF_Coop_Operation_Rescue/FAF_Coop_Operation_Rescue_script.lua

Fix conditions for completing truck objective
