X1CA_Coop_001/X1CA_Coop_001_script.lua
These lines remove the intel blips and buildings for the base revealed in the intro, so advanced players will need intel of their own.
=> Hide bases for highest difficulty

X1CA_Coop_002/X1CA_Coop_002_script.lua
There were different names for ally ACUs in save.lua and script.lua
=> FA M2 Map not expanding fix

SCCA_Coop_R06/SCCA_Coop_R06_script.lua
Added restrictions to T3 Mobile AA + fixed restrictions for other factions units. Restriction needs to be set on player. No need to restrict AI, it wont build them unless its scripted.
=> C M6 - Fixed Restrictions

SCCA_Coop_R05/SCCA_Coop_R05_script.lua
Table with human players was missing, Map was not expanding after first objective when game tried to remove restrictions from all human players.
=> Cybran M5 not expanding

SCCA_Coop_A03/SCCA_Coop_A03_script.lua
pause player's mass fabs at the beginning since they dont consume only 40e as they did in vanilla
=> Aeon M3 Pausing mass fabs

SCCA_Coop_A02/SCCA_Coop_A02_script.lua, SCCA_Coop_A03/SCCA_Coop_A03_script.lua, SCCA_Coop_A04/SCCA_Coop_A04_script.lua, SCCA_Coop_A05/SCCA_Coop_A05_script.lua, SCCA_Coop_A06/SCCA_Coop_A06_script.lua, SCCA_Coop_E04/SCCA_Coop_E04_script.lua, SCCA_Coop_E05/SCCA_Coop_E05_script.lua, SCCA_Coop_E06/SCCA_Coop_E06_script.lua, SCCA_Coop_R02/SCCA_Coop_R02_script.lua, SCCA_Coop_R03/SCCA_Coop_R03_script.lua, SCCA_Coop_R04/SCCA_Coop_R04_script.lua, SCCA_Coop_R05/SCCA_Coop_R05_script.lua, SCCA_Coop_R06/SCCA_Coop_R06_script.lua
Redone restrictions for Cybran and UEF campaign and added them for Aeon campaign as well. Better way than in #54 
And fixes  part of #53
=> Easier way to restrict FA units in vanilla

X1CA_Coop_006/X1CA_Coop_006_script.lua
It turned out that this file
https://github.com/FAForever/faf-coop-maps/commit/9272a93db8b9765632409adebaa29469685d5d61
was actually used here. Whoever thought this was a good idea is bad and
should feel bad.
Fixed FA M6 not starting. Original report http://forums.faforever.com/forums/viewtopic.php?f=3&t=10798#p110000
=> Don't import file from different mission

X1CA_Coop_001/X1CA_Coop_001_script.lua
Some of the voice overs are just for UEF and Aeon and new system for
voice overs didn't count with that. So if Leader Faction was cybran and
script get the this point, it bugged out and map didn't expand after
finishing objectives.
=> Dont try to play VOs for cybran that don't exist

X1CA_Coop_003/X1CA_Coop_003_m1rhizaai.lua, X1CA_Coop_006/X1CA_Coop_006_m2rhizaai.lua
Added build condition that is in all OpAI attacks. No longer build units
when base is set as inactive. That is a case when friendly AI ACU
teleports out cause of taking too much damage. Custom platoons were
missing this build condition.
=> Stop Custom Plattons when Base Set Inactive

SCCA_Coop_R01/SCCA_Coop_R01_script.lua
Fixes #102
New restriction system would delete it when the unit is transfered to
new army, that has it restricted, on capture
=> Temporarily allow T2 Radar

ThetaCivilianRescue/ThetaCivilianRescue_script.lua
I changed some unit restrictions so players could capture cybran mex and pgen without them dissappearing. (Cybran T3 mex is available now, but don't know how to allow t3 mex to be captured, without allowing the player to upgrade them to t3.)
=> Adjust restrictions to allow Cybran building capture

ThetaCivilianRescue/ThetaCivilianRescue_script.lua
Players would see entire map at start.
Now they are immediatly put in the initial camera position and can ony see the initial playable area.
=> Fix initial player view in OnStart

SCCA_Coop_R04/SCCA_Coop_R04_script.lua
The trigger for the function EnemyCommanderDied has been changed from a unit death trigger to an objective complete callback. This will prevent the ending cut scene from playing twice. 
This will resolve Issue #233
=> Cybran M4 - Changed how the Aeon Commander death cutscene triggers

FortClarkeAssault/FortClarkeAssault_script.lua
For some reason when you kill the ACU, the objective is counting that as
a killing 2, the callback function in objective is called twice if there
is another callback funciton in OnKilled trigger. This will need to be
investigated later.
Fixes #243
=> Remove cam on dead ACUs

SCCA_Coop_A01/SCCA_Coop_A01_script.lua
Main UEF ACU has the same dialogue when dying as the junior ACU, it
looks like it always was this case.
Fixes #248
=> Dont play same dialogue for both UEF ACUs

X1CA_Coop_005/X1CA_Coop_005_script.lua
After the Scathis rework, it's OP when it starts shooting right after
the map expansion.
Fixes #350
=> Disable Scathis in Hex5 base

FAF_Coop_Prothyon_16/FAF_Coop_Prothyon_16_scenario.lua, FAF_Coop_Theta_Civilian_Rescue/FAF_Coop_Theta_Civilian_Rescue_scenario.lua, SCCA_Coop_A01/SCCA_Coop_A01_scenario.lua, SCCA_Coop_A02/SCCA_Coop_A02_scenario.lua, SCCA_Coop_A03/SCCA_Coop_A03_scenario.lua, SCCA_Coop_A04/SCCA_Coop_A04_scenario.lua, SCCA_Coop_E01/SCCA_Coop_E01_scenario.lua, SCCA_Coop_E02/SCCA_Coop_E02_scenario.lua, SCCA_Coop_E03/SCCA_Coop_E03_scenario.lua, SCCA_Coop_E04/SCCA_Coop_E04_scenario.lua, SCCA_Coop_E05/SCCA_Coop_E05_scenario.lua, SCCA_Coop_E06/SCCA_Coop_E06_scenario.lua, SCCA_Coop_R01/SCCA_Coop_R01_scenario.lua, SCCA_Coop_R02/SCCA_Coop_R02_scenario.lua, SCCA_Coop_R03/SCCA_Coop_R03_scenario.lua, SCCA_Coop_R05/SCCA_Coop_R05_scenario.lua, SCCA_Coop_R06/SCCA_Coop_R06_scenario.lua, X1CA_Coop_001/X1CA_Coop_001_scenario.lua, X1CA_Coop_002/X1CA_Coop_002_scenario.lua, X1CA_Coop_003/X1CA_Coop_003_scenario.lua, X1CA_Coop_004/X1CA_Coop_004_scenario.lua, X1CA_Coop_005/X1CA_Coop_005_scenario.lua, X1CA_Coop_006/X1CA_Coop_006_scenario.lua
Game doesnt use it and doesnt need it, but the GPG editor crashes
without it.
=> Add norushradius into scenario.lua

SCCA_Coop_A05/SCCA_Coop_A05_script.lua
Fixed a bug due to which, after the destruction of the civilian colony, the mission was not considered failed.
=> SCCA_Coop_A05 bug fixed

SCCA_Coop_A02/SCCA_Coop_A02_script.lua
Fixes a bug that can break Aeon mission 2 if the stealthed base is detected too soon (causing the stealthed base objective to trigger first, which breaks the mission if mission 2 (of mission 2) hasn't triggered yet.
For further details see:
https://discord.com/channels/944679492293636116/944697747376853003/1132011694131007569
=> Fix Aeon M2 objective SCCA_Coop_A02_script.lua

SCCA_Coop_A02/SCCA_Coop_A02_script.lua
I had a game where the map wouldn't expand after the attackers were killed.  Adding in logs to this revealed all the M3Attackers were returning true for :IsDead(). Adding in the code to force the next mission objective to run if all attackers are dead resolved the issue and meant the map expanded.
=> Aeon M2 - Fix bug with map not expanding if attackers killed quickly

SCCA_Coop_A04/SCCA_Coop_A04_script.lua
Previous reference was invalid, resulting in a lua error. E.g.:
WARNING: Error running lua script: ...ce\maps\scca_coop_a04.v0021\scca_coop_a04_script.lua(833): access to nonexistent global variable GetNumOfHumanUnits
stack traceback:
[C]: in function `error'
...ata\faforever\gamedata\lua.nx2\lua\system\config.lua(54): in function <...ata\faforever\gamedata\lua.nx2\lua\system\config.lua:53>
...ce\maps\scca_coop_a04.v0021\scca_coop_a04_script.lua(833): in function `callback'
...\faforever\gamedata\lua.nx2\lua\scenariotriggers.lua(221): in function <...\faforever\gamedata\lua.nx2\lua\scenariotriggers.lua:203>
While the error doesn't break the mission, it impacts the air attacks that are sent.
=> Fix AI air attack - Aeon Mission 4

SCCA_Coop_E03/SCCA_Coop_E03_script.lua
=> Fix trigger to account for all players

SCCA_Coop_A04/SCCA_Coop_A04_script.lua
Fixes error when game tries assigning units to a platoon that doesnt exist
=> Aeon M4 fix bug with missing transport platoon

SCCA_Coop_R04/SCCA_Coop_R04_script.lua
When testing to fix another (more common) issue I ran into the scenario where it tried completing mission 2 before it had started mission 2.  This adds a redundancy to call the start of M2 first in this scenario, while also avoiding triggering the start of M2 multiple times as a result of the redundancy
=> Cybran M4 - fix bug where M2 can be completed before it has started

SCCA_Coop_R04/SCCA_Coop_R04_script.lua
Adds redundancy for an issue/error message that can occur if the player is able to capture one of the nodes before the video briefing has completed
=> Cybran M4 fix where player is quicker than intro

X1CA_Coop_003/X1CA_Coop_003_script.lua
Following FAF changes introducing external factory units, these get included as part of the objective to be destroyed, but the objective doesn't complete when the parent unit is destroyed (presumably the OnKilled callback doesnt trigger for the external factory when it is removed due to the parent dying) Fix is to just exclude external factories from the list of units added to the objective.
=> FA M3 Red Dawn: Fix bug with 1st mission completion due to external factories

SCCA_Coop_A01/SCCA_Coop_A01_Strings.lua, SCCA_Coop_A02/SCCA_Coop_A02_strings.lua, SCCA_Coop_A03/SCCA_Coop_A03_strings.lua, SCCA_Coop_A06/SCCA_Coop_A06_strings.lua
Fixes some incorrect briefing cue orders for VO in certain Aeon missions.
Specifically:
AEON M1 - Voice cue order fixed
AEON M2 - Voice cue order fixed
AEON M3 - Voice cue order fixed
AEON M6 - Voice cue order fixed
=> Fix some incorrect Aeon briefing VO cue orders

X1CA_Coop_002/X1CA_Coop_002_script.lua
Checks that nuke launchers are alive before giving them missiles (covers niche cases where the nuke launchers might be killed, e.g. by AI)
=> FA M2 Fix - Check nuke launchers alive (Dawn (X1CA_Coop_002))
